spring:
    redis:
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6379}
        password: ${REDIS_PASSWORD:}

# slack
slack:
    webhook:
        token: ${SLACK_WEBHOOK_TOKEN:}
        id: ${SLACK_WEBHOOK_ID:}
        service-alarm-channel :  ${SLACK_SERVICE_CHANNEL_ID:}
        username: ${SLACK_WEBHOOK_USERNAME:Idp-Service-Alarm}
        icon-url: ${SLACK_WEBHOOK_ICON_URL:}