auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY:testkeytestkeytestkeytestkeytestkeytestkeytestkeytestkeytestkey}
    access-exp: ${JWT_ACCESS_EXP:3600}
    refresh-exp: ${JWT_REFRESH_EXP:86400}
    # Redis Dependencies - Login, Logout ????
#spring.jwt.secret-key =SECRET_KEY
#spring.jwt.blacklist.access-token =BlackList_AccessToken_
#spring.main.allow-bean-definition-overriding=true